#!/bin/bash

# Misc
BACKEND=$XDG_SESSION_TYPE
FONT="Ubuntu Mono 11"
LINE_HEIGHT=20

# Colors
TITLE_BG=1d2021
TITLE_FG=d3869b
FILTER_BG=1d2021
FILTER_FG=d3869b
NORMAL_BG=1d2021
NORMAL_FG=a89984
HIGHLIGHTED_BG=1d2021
HIGHLIGHTED_FG=8ec07c
SCROLLBAR_FG=ebdbb2

COLORS="--tb=#$TITLE_BG --tf=#$TITLE_FG --fb=#$FILTER_BG --ff=#$FILTER_FG --nb=#$NORMAL_BG --nf=#$NORMAL_FG --hb=#$HIGHLIGHTED_BG --hf=#$HIGHLIGHTED_FG --scf=#$SCROLLBAR_FG"

function run() {
    BEMENU_OPTS="$COLORS --ignorecase --fn \"$FONT\" --line-height=$LINE_HEIGHT --prompt \"$2\""
    env BEMENU_BACKEND=$BACKEND BEMENU_OPTS="$BEMENU_OPTS" $1
}
